### ISSUE TITLE
three.js considerations

### ISSUE THREAD

**Issue by davidhoness** [trinketapp/3D-testing#6]
Hi folks, this [stackoverflow](http://stackoverflow.com/questions/11243689/prefered-3d-model-format-of-three-js) article might be of interest to you regarding model formats.

Please let me know asap if you need us to undertake 3D modelling work.

**Comment by eah13** [comment]
Thanks for finding this! We'll definitely need some help with modelling. For now we're using something that looks like this for mock-up purposes:

![screenshot 2017-02-15 at 12 57 03 pm](https://cloud.githubusercontent.com/assets/1702745/23022316/24338640-f41e-11e6-8538-433a2470dee9.png)

It was created from tridiv.com and is pure HTML/CSS. We're trying to avoid WebGL if we can since SVGs get bitmapped and ourt logic won't work with them. Can hop on a quick call letter today if that's helpful. We may be able to model ourselves but at the moment it's looking like getting a designer to build something in tridiv would be ideal.

**Comment by eah13** [comment]
I made the above in 5 minutes with a ruler and a Sense HAT, for reference.

**Comment by eah13** [comment]
three.js + tridiv model deployed! closing this.
