### ISSUE TITLE
Fire Fox + IE 'flat' 3D Fallback

### ISSUE THREAD

**Issue by davidhoness** [trinketapp/3D-testing#7]
![trinket ff depth issue](https://cloud.githubusercontent.com/assets/6640424/23798012/8346ec20-059a-11e7-8c60-e868b693b4ef.png)

Screen shot from Fire Fox 52 (64 bit) on Ubuntu.

I'm aware that TriDiv doesn't support Fire Fox and this is probably why, it has depth drawing problems. Can you let me know if anything can be done about this? If not we will probably have to make the decision to not support FF. The rendering performance was also pretty slow compared to Chrome on the same machine.

**Comment by eah13** [comment]
Researching whether there are any workarounds.  [This article](https://css-tricks.com/things-watch-working-css-3d/) (ctrl-F for Firefox) has a minimal example and claims that FF just plain doesn't get 3d shape ordering right.  I can't find much on the Web about this, which surprises me

**Comment by eah13** [comment]
As per our discussion, we'll create a flat/simple fallback for Firefox and probably Edge with a message to upgrade to a browser that supports 3d for the full experience.

**Comment by ebertmi** [comment]
Those seems to be relevant to our issue with FireFox and 3d transforms:

https://bugzilla.mozilla.org/show_bug.cgi?id=1286716
https://bugzilla.mozilla.org/show_bug.cgi?id=725299
https://bugzilla.mozilla.org/show_bug.cgi?id=1097464
https://bugzilla.mozilla.org/show_bug.cgi?id=689498

All of those bugs can are related to `preserve-3d` and plane ordering.

**Comment by eah13** [comment]
Changed this issue title to reflect the planned strategy for addressing this: using a 'flat' 3d model fallback for FF + IE that side-steps the non-support for `preserve-3d`.  Since the bug is only visible when there are multiple 3D volumes, we need to limit it to only one.

If there is support for a 3d volume with depth, and we can get design assets for all 6 sides, we may be able to provide a single cuboid for this fallback mode instead of a flat 2d image in 3d space.

**Comment by eah13** [comment]
This is implemented!
